# Generated by Django 5.2.14 on 2026-05-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200, verbose_name='Группа / исполнитель')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='covers/%Y/%m/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist'], name='collection__artist_4e3bbf_idx'), models.Index(fields=['title'], name='collection__title_2d7010_idx')],
            },
        ),
    ]
