# Generated by Django 5.2.14 on 2026-05-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/%Y/%m/', verbose_name='Обложка'),
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='albums/%Y/%m/', verbose_name='Фото')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='collection.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'фото альбома',
                'verbose_name_plural': 'фото альбомов',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
