"""Точные страницы Wikipedia для альбомов с ошибочным автоподбором."""

# (artist, title в базе) -> название страницы Wikipedia
WIKI_PAGE_OVERRIDES: dict[tuple[str, str], str] = {
    ('Alan Freeman', 'By Invitation Only'): 'By Invitation Only (Alan Freeman album)',
    ('Alvin Lee & Ten Years After', 'At Their Best'): 'At Their Best (Ten Years After album)',
    ('Black Sabbath', '13'): '13 (Black Sabbath album)',
    ('Bonamassa Joe', 'Muddy Wolf at Red Rocks'): 'Muddy Wolf at Red Rocks',
    ('Grand Funk Railroad', 'Caught in the Act'): 'Caught in the Act (Grand Funk Railroad album)',
    ('Graveyard', 'Live At...'): 'Live at Roadburn 2015 (Graveyard album)',
    ('Imelda May', 'Love Tattoo'): 'Love Tattoo',
    ('Jimi Hendrix', 'Blues'): 'Blues (Jimi Hendrix album)',
    ('Led Zeppelin', 'II'): 'Led Zeppelin II',
    ('Led Zeppelin', 'III'): 'Led Zeppelin III',
    ('Led Zeppelin', 'IV'): 'Led Zeppelin IV',
    ('Led Zeppelin', 'Coda'): 'Coda (Led Zeppelin album)',
    ('Led Zeppelin', 'Led Zeppelin'): 'Led Zeppelin (album)',
    ('Mungo Jerry', 'In the Summertime (The Best of)'): 'In the Summertime (album)',
    ('Opeth', 'Heritage'): 'Heritage (Opeth album)',
    ('Opeth', 'Last'): 'Pale Communion',
    ('Opeth', 'Sorceress'): 'Sorceress (Opeth album)',
    ('Paul McCartney', 'Ram'): 'Ram (album)',
    ('Queen', 'A Night at the Odeon'): 'A Night at the Odeon – Hammersmith 1975',
    ('Queen', 'Live Magic'): 'Live Magic',
    ('Queen', 'News of the World'): 'News of the World (Queen album)',
    ('Rival Sons', 'Pressure&Time'): 'Pressure & Time',
    ('Ten Years After', 'Woodstock'): 'Undead (Ten Years After album)',
    ('The Answer', 'Sundowners'): 'Sundowners (The Answer album)',
    ('The Beatles', 'Magical Mystery Tour'): 'Magical Mystery Tour',
    ('The Beatles', 'Sergant Pepper'): "Sgt. Pepper's Lonely Hearts Club Band",
    ('The Beatles', 'The Beatles (White Album)'): 'The Beatles (album)',
    ('The Beatles', 'With the Beatles'): 'With the Beatles',
    ('The Mars Volta', 'Octahedron'): 'Octahedron (album)',
    ('The Tangent', 'Proxy'): 'Proxy (The Tangent album)',
    ('Steve Hackett', 'The Circus And The Nightwhale'): 'The Circus and the Nightwhale',
    ('Vangelis', 'Blade Runner'): 'Blade Runner (soundtrack)',
    ('Various Artists', 'Blues Greatest'): 'Blues',
    ('Пикник', 'Иероглиф'): 'Иероглиф (альбом)',
}
